[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
  base = "/"

# Для SPA, наприклад React (можна увімкнути, якщо потрібна підтримка роутів через reload)
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
