export const furniture = [
  { id: 1, name: "Письмовий стіл", category: "Столи" },
  { id: 2, name: "Обідній стіл", category: "Столи" },
  { id: 3, name: "Журнальний стіл", category: "Столи" },
  { id: 4, name: "Кухонний стіл", category: "Столи" },
  { id: 5, name: "Стіл-трансформер", category: "Столи" },
  { id: 6, name: "Скляний стіл", category: "Столи" },
  { id: 7, name: "Стіл для ноутбука", category: "Столи" },
  { id: 8, name: "Стіл з висувними ящиками", category: "Столи" },
  { id: 9, name: "Стіл-консоль", category: "Столи" },
  { id: 10, name: "Комп'ютерний стіл", category: "Столи" },

  { id: 11, name: "Офісний стілець", category: "Стільці" },
  { id: 12, name: "Дерев'яний стілець", category: "Стільці" },
  { id: 13, name: "Барний стілець", category: "Стільці" },
  { id: 14, name: "Крісло-стілець", category: "Стільці" },
  { id: 15, name: "Стілець для ванної", category: "Стільці" },
  { id: 16, name: "Стілець з м’яким сидінням", category: "Стільці" },
  { id: 17, name: "Складний стілець", category: "Стільці" },
  { id: 18, name: "Стілець-гойдалка", category: "Стільці" },
  { id: 19, name: "Дитячий стілець", category: "Стільці" },
  { id: 20, name: "Стілець без спинки", category: "Стільці" },

  { id: 21, name: "Шафа-купе", category: "Шафи" },
  { id: 22, name: "Книжкова шафа", category: "Шафи" },
  { id: 23, name: "Кухонна шафа", category: "Шафи" },
  { id: 24, name: "Шафа для одягу", category: "Шафи" },
  { id: 25, name: "Настінна шафа", category: "Шафи" },
  { id: 26, name: "Шафа з дзеркалом", category: "Шафи" },
  { id: 27, name: "Кутова шафа", category: "Шафи" },
  { id: 28, name: "Шафа для взуття", category: "Шафи" },
  { id: 29, name: "Комбінована шафа", category: "Шафи" },
  { id: 30, name: "Шафа з полицями", category: "Шафи" },

  { id: 31, name: "Прямий диван", category: "Дивани" },
  { id: 32, name: "Кутовий диван", category: "Дивани" },
  { id: 33, name: "Розкладний диван", category: "Дивани" },
  { id: 34, name: "Диван-ліжко", category: "Дивани" },
  { id: 35, name: "Диван з отоманкою", category: "Дивани" },
  { id: 36, name: "Модульний диван", category: "Дивани" },
  { id: 37, name: "Компактний диван", category: "Дивани" },
  { id: 38, name: "Диван для вітальні", category: "Дивани" },
  { id: 39, name: "Дизайнерський диван", category: "Дивани" },
  { id: 40, name: "Ретро диван", category: "Дивани" },
];
